
# Theme
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
# Head info
head:
    favicon: "/img/logo.png"
    keywords: SYTV, 西苑高中, 資訊志工隊, 西苑高中資訊志工隊, SYSH Tech Volunteer
    backgroundpic : "img/team.jpg"

Intro:
    name: SYTV
    slogan: "西苑高中資訊志工隊"
    HeadButton: SYTV 西苑高中資訊志工隊

Nav:
    Home_name: 首頁
    is_use_categories : true 
    categories_name: 分類
    is_use_archives : false
    archives_name: 檔案
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        github: https://github.com/SYSH-Tech-Volunteer
        discord: https://discord.gg/D8wFzrC5At
        
    pages:
        關於 :
            link: "/about/"
        成員 :
            link: "/group/"
        活動 :
            link: "/gallery/"
        聯絡 :
            link: "/tag/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: 關於我們
    description: 西苑高中資訊志工隊是西苑高中的資訊志工隊。<br>我們會協助學校處理資訊相關問題，以及辦理資訊主題營隊。
    pic_url: /img/team.jpg
    goto_ulr: "https://github.com/SYSH-Tech-Volunteer"

Gallery :
    title: 活動照片
    description: 這裡是我們的活動照片，

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: "Noto Sans TC", "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: false
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: false
       appId: 'your appId'
       appKey: 'your appkey'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML